name: Manual
on:
  push:
    branches:
      - master

jobs:
  download-image:
    name: download image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      
      - name: install gem twitter
        run: gem install twitter
      
      - name: make public directory
        run: mkdir public
      
      - name: work
        run: |
          cp hitokoto.rb public/hitokoto.rb
          cp query.txt public/query.txt
          cp allowlist.txt public/allowlist.txt
          cp default.jpg public/hitokoto.jpg
          cp manual_url.txt public/manual_url.txt
          cd public
          ruby hitokoto.rb ${{secrets.TWITTER_CONSUMER_KEY}} ${{secrets.TWITTER_CONSUMER_SECRET}} ${{secrets.TWITTER_ACCESS_TOKEN}} ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}} > output_log.txt
          rm hitokoto.rb
          rm query.txt
          rm allowlist.txt
          rm manual_url.txt
          #rm output_log.txt
          cd ../
        
      ### DEPLOY ###
      # https://qiita.com/syui/items/f1f2db8660cda34d8938
      # https://github.com/peaceiris/actions-gh-pages
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public
