name: Ruby
on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        version: 2.7
    - name: Build
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: lint
      run: bundle exec rubocop
    - name: rspec
      run: bundle exec rspec
