name: Ruby
on:
  #schedule:
    # 気象庁が発表している更新のタイミング
    #  5, 11, 17 (JST, UTC+09)
    # 更新が確認された時間(上記を含む)
    #  5,  6,  7,  8,  9, 10, 11, 12, 13, 17, 18, 19, 20, 21, 22, 23 (JST, UTC+09)
    # 20, 21, 22, 23,  0,  1,  2,  3,  4,  8,  9, 10, 11, 12, 13, 14 (GMT)
    # デーモンプロセス設定 (世界標準時)
    #- cron: 10 0-15,20-23 * * *
  push:
    branches:
      - master

jobs:
  download-image:
    name: download image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: make public directory
        run: mkdir public
  
      #- name: make README.md
      #  run: echo "TEST" > public/README.md
          
      - uses: actions/checkout@master
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          version: 2.7
      - name: download with ruby
        run: |
          touch public/url_list.txt
          cat README.md > public/url_list.txt
     
      - name: make url list
        run: |
          ls -al > public/url_list.txt
          ruby test.rb ${{secrets.TWITTER_CONSUMER_KEY}} ${{secrets.TWITTER_CONSUMER_SECRET}} ${{secrets.TWITTER_ACCESS_TOKEN}} ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}} > public/output_log.log
      
      ### DEPLOY ###
      # https://qiita.com/syui/items/f1f2db8660cda34d8938
      # https://github.com/peaceiris/actions-gh-pages
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: public 
